// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WORKFLOW.Model.Context;

#nullable disable

namespace WORKFLOW.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20230410080328_add_master_group_workflow")]
    partial class add_master_group_workflow
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WORKFLOW.Model.db.md_groupworkflow", b =>
                {
                    b.Property<string>("groupworkflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("groupworkflowcode");

                    b.Property<string>("username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("groupworkflowcode", "username")
                        .HasName("md_groupworkflow_PRIMARY");

                    b.ToTable("md_groupworkflow");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_rule_exp", b =>
                {
                    b.Property<string>("workflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflowcode");

                    b.Property<string>("rulecode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rulecode");

                    b.Property<int>("groupline")
                        .HasColumnType("integer")
                        .HasColumnName("groupline");

                    b.Property<string>("paramcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paramcode");

                    b.Property<int>("linenum")
                        .HasColumnType("integer")
                        .HasColumnName("linenum");

                    b.Property<string>("linkexp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("linkexp");

                    b.Property<string>("paramname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paramname");

                    b.Property<string>("paramsexpression")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("paramsexpression");

                    b.HasKey("workflowcode", "rulecode", "groupline", "paramcode")
                        .HasName("md_rule_exp_PRIMARY");

                    b.ToTable("md_rule_exps");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_rule_var", b =>
                {
                    b.Property<string>("workflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflowcode");

                    b.Property<string>("rulecode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rulecode");

                    b.Property<string>("paramcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paramcode");

                    b.Property<int>("linenum")
                        .HasColumnType("integer")
                        .HasColumnName("linenum");

                    b.Property<string>("paramname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paramname");

                    b.Property<string>("paramsexpression")
                        .IsRequired()
                        .HasMaxLength(9999999)
                        .HasColumnType("character varying(9999999)")
                        .HasColumnName("paramsexpression");

                    b.HasKey("workflowcode", "rulecode", "paramcode")
                        .HasName("md_rule_var_PRIMARY");

                    b.ToTable("md_rule_vars");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_workflow", b =>
                {
                    b.Property<string>("workflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflowcode");

                    b.Property<string>("paramcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paramcode");

                    b.Property<string>("paramname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("paramname");

                    b.Property<string>("paramsexpression")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("paramsexpression");

                    b.HasKey("workflowcode", "paramcode")
                        .HasName("md_workflow_PRIMARY");

                    b.ToTable("md_workflow");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_groupworkflow", b =>
                {
                    b.Property<string>("groupworkflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("groupworkflowcode");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdate");

                    b.Property<string>("groupworkflowname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("groupworkflowname");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("groupworkflowcode");

                    b.ToTable("ms_groupworkflow");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_rule", b =>
                {
                    b.Property<string>("workflowcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflowcode");

                    b.Property<string>("rulecode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rulecode");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdate");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enddate");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("rulename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rulename");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startdate");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.HasKey("workflowcode", "rulecode")
                        .HasName("ms_rule_PRIMARY");

                    b.ToTable("ms_rule");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_workflow", b =>
                {
                    b.Property<string>("workflowCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("workflowcode");

                    b.Property<DateTime>("createdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdate");

                    b.Property<bool>("isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedate");

                    b.Property<string>("workflowname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflowname");

                    b.HasKey("workflowCode");

                    b.ToTable("ms_workflow");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_groupworkflow", b =>
                {
                    b.HasOne("WORKFLOW.Model.db.ms_groupworkflow", null)
                        .WithMany("md_groupworkflows")
                        .HasForeignKey("groupworkflowcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_rule_exp", b =>
                {
                    b.HasOne("WORKFLOW.Model.db.ms_rule", null)
                        .WithMany("md_rule_exps")
                        .HasForeignKey("workflowcode", "rulecode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_rule_var", b =>
                {
                    b.HasOne("WORKFLOW.Model.db.ms_rule", null)
                        .WithMany("md_rule_vars")
                        .HasForeignKey("workflowcode", "rulecode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WORKFLOW.Model.db.md_workflow", b =>
                {
                    b.HasOne("WORKFLOW.Model.db.ms_workflow", null)
                        .WithMany("md_workflows")
                        .HasForeignKey("workflowcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_rule", b =>
                {
                    b.HasOne("WORKFLOW.Model.db.ms_workflow", null)
                        .WithMany("ms_rules")
                        .HasForeignKey("workflowcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_groupworkflow", b =>
                {
                    b.Navigation("md_groupworkflows");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_rule", b =>
                {
                    b.Navigation("md_rule_exps");

                    b.Navigation("md_rule_vars");
                });

            modelBuilder.Entity("WORKFLOW.Model.db.ms_workflow", b =>
                {
                    b.Navigation("md_workflows");

                    b.Navigation("ms_rules");
                });
#pragma warning restore 612, 618
        }
    }
}
